cstore_fdw.c
cstore_fdw.h

acquired an exclusive lock at CStoreBeginForeignModify and released the lock at CStoreEndForeignModify. 
locked relation pointer is kept at TableWriteState during the operation.

fixes bug #47 related to concurrent inserts

---

cstore_fdw.c

Previously we were using Exclusive locks to protect concurrent INSERTs from each other. But since PostgreSQL acquires RowExclusive locks automatically before executing cstore's insert logic, and Exclusive & RowExclusive locks conflict, this resulted in deadlock.
This pull request fixes this by using ShareUpdateExclusive locks, which is self-conflicting, but doesn't conflict with RowExclusive locks.

Fixed the deadlock issue for concurrent inserts.

---

cstore_fdw.c

cstore_fdw tries to determine if given table is infact a cstore table during copy operation. However,  if given name is not a table at all, cstore fails at this stage and stops copy processing altogether. 
This change  enables cstore_fdw to determine whether a given name is a cstore_fdw table without affecting the rest of copy handling.  If an error is encountered, cstore_fdw stops its own handling only instead of stopping the whole copy operation.

Fix copy with transmit option when used in Citus

---

cstore_fdw.c
cstore_fdw.h

With the new COPY for distributed tables in Citus, we need a way to skip cstore_fdw's COPY implementation for distributed columnar tables. Since citus always needs to come first in shared_preload_libraries, cstore_fdw's ProcessUtility hook always overrides citus' ProcessUtility hook and thus comes first.
After this change, when issuing a COPY command on a columnar table, cstore_fdw first checks whether the Citus extension is loaded, the pg_dist_partition table exists, and  pg_dist_partition contains a record for the cstore_fdw table. If so it lets the COPY fall through to citus.

Let Citus handle COPY on distributed cstore_fdw tables

---

cstore_fdw.c
expected/alter.out
sql/alter.sql

We relied on PostgreSQL to to type checking and did not verify anything at extension level.
This has caused some usability issues when column type is altered to incompatible type.
We now perform compatibility check for alter table statement before letting standard utility to handle the command.
Fixes #71

Add alter column type verifications to prevent incorrect changes

---

cstore_fdw.c
expected/query.out
sql/query.sql

Postgresql does not reduce some function calls in target list when used in ```union all``` queries. This change uses ```pull_var_clause()``` to detect Var's used in target list when detecting which columns should be returned for the query on cstore table.
Fixes #107 and #95

Reduce function calls to var's during requested column computation

---

cstore_reader.c

Some columns to cstore table might be added after some data was ingested. This makes earlier stripes to not to have appropriate value for ColumnBlockSkipNode. Earlier work initialized them to be default values. However initialization code was faulty and did not initialize all blocks properly.
This issue was found by a user. 
Fixes #135

Fix incorrect initialization of columnSkipList for missing columns

---

cstore_fdw.c

Copy in loop calls ```CHECK_FOR_INTERRUPTS();``` after each row insert to enable cancelling. Some content is written to data file, but since footer is not updated they won't be visible.
One down side is that written content still takes space in disk until being overwritten by subsequent copy or insert calls.
Fixes #145

Enable cancelling copy in

---

.travis.yml
Makefile
cstore_fdw.c

There are some API changes regarding process utility hooks,
raw_parser(), and DoCopy() function.
Added conditional conditional compilation definitions to
make cstore_fdw run with PG 10 without breaking compatibility for
previously supported PG versions (9.3, 9.4, 9.5, 9.6)

Add support for Postgres 10

---

cstore_fdw.c
expected/drop.out
sql/drop.sql

This PR addresses an issue when a foreign server is created inside a template database, newly created databases can not create foreign tables due to missing folder. This fix makes sure required directroy exists prior to creating files in it.
This also makes sure that cstore files are removed after a database or cstore extension is dropped out of current database.
There are 2 mishaps that we can't address
- if the cstore table is created with file name option, there is no way of removing it when a database/extension is dropped
- if the active database does not have cstore extension created, then we can't reclaim resources of the dropped database.
Fixes : #124 , #129

Directory creation and cleanup after database operations

---

cstore_fdw.c
cstore_reader.c

A user reported performance issue if all stripe skip lists are
deserialized even if only a fraction of them is selected. 
Fixes #136

Read stripe skip list only if column is referenced by the query

---

cstore_fdw.c
expected/truncate.out
sql/truncate.sql

We rely on postgres to do access control checks for all functions. However, since truncate for cstore tables is handled in process utility,  not forwarded to postgres, and we did not check if a user has truncate right on the table, we let unprivileged user to perform truncate.
This fix introduces acl check prior to truncating files, and reports error if user has failed the check.
Fixes #148

Check if the user has truncate privilege on the table

---

cstore.proto

Without this, we get the following build warning: "No syntax specified for the proto file: cstore.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)".

Specify protobuf syntax version.

---

cstore_fdw.c

We are blindly running ```rmtree()``` command to remove a database folder under ``cstore_fdw``` folder. 
This PR introduces a check before actually deleting the folder.
Fixes #157

Check if folder exists before issuing delete command

---

cstore_fdw.c
expected/truncate.out
sql/truncate.sql

This is the final patch for the fix worked on in #182 
It is a rebase on master keeping the first 2 commits (fix and regression test) melted in one.

fix a segfault when processing truncate in cached plans (final version)

---

.travis.yml
README.md

`libprotobuf-c0-dev` and `protobuf-c-compiler` conflict: 
user@machine:~$ sudo apt-get install libprotobuf-c0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
libprotobuf-c1 libprotobuf9v5 libprotoc9v5
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
libprotobuf-c-dev protobuf-c-compiler
..........
user@machine:~$ sudo apt-get install protobuf-c-compiler
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
libprotobuf-c0
Use 'sudo apt autoremove' to remove it.
The following additional packages will be …

Fix `cstore_fdw` dependency instructions

---

cstore_fdw.c

Fixes #196 
Implement the BeginForeignInsert and EndForeignInsert to properly support COPY and insert in Postgres 11.

Add support for Postgres 11 COPY

---

cstore_fdw.c

Fixes #178 
There's no reason why parallel scans of a cstore_fdw table would not be safe right now. Multiple processes can read from tables in parallel and there is no state kept between individual statements, which means that another process (like a parallel worker) can read everything that was written. 
Partially addresses #161 
Based it against master because develop does not have PG11 support

Mark foreign scan as parallel safe

---

Makefile

Postgresql has recently changed its build environment for OSX.
We need to have /usr/local/include in PG_CPPFLAGS to be able to access
protobuf-c headers.
Related to #193

Fix OSX build failure

---

README.md

The installation prerequisites in README.md don't work anymore on Ubunutu 18.04 because the package `libprotobuf-c0-dev` seems to have disappeared. However, there is a package called `libprotobuf-c-dev`, and the installation works with it. 
This PR adapts README.md accordingly

Adapt installation instructions for Ubuntu 18.4+

---

.travis.yml
Makefile
cstore_compression.c
cstore_fdw.c
cstore_reader.c
cstore_version_compat.h
cstore_writer.c

- fix the build
- revisit data file naming method. (use the old logic in pre-pg12)

pg12 compatibility related changes

---

cstore_fdw.c
expected/alter.out
sql/alter.sql

We are failing to eliminate dropped column when we are enumerating columns to project.
Thus queries like `select count(t.*) from table t` or `select t from table t` were failing.
Fixes : #217

Fix count(t.*) type queries after column drop
